--- #YAML:1.0
name:               POE-Session-MessageBased
version:            0.111
abstract:           Message-based events for POE (no @_ slices)
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:         1.007
    Test::More:  0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rcaputo/poe-session-messagebased
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
